$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: diabetes-pipeline-github

settings:
  default_datastore: azureml:workspaceblobstore

jobs:

  fix_missing_job:
    type: command
    inputs:
      raw_data:
        path: azureml:diabetes-data:1
    outputs:
      prep_data:
        mode: upload
    code: model
    environment: azureml:basic-env-scikit:2
    compute: azureml:aml-cluster
    command: >-
      python fix-missing-data.py 
      --input_data ${{inputs.raw_data}} 
      --output_data ${{outputs.prep_data}}

  normalize_job:
    type: command
    inputs:
      clean_data: ${{parent.jobs.fix_missing_job.outputs.prep_data}}
    outputs:
      normalized_data:
      mode: upload
    code: model
    environment: azureml:basic-env-scikit:2
    compute: azureml:aml-cluster
    command: >-
      python normalize-data.py 
      --input_data ${{inputs.clean_data}} 
      --output_data ${{outputs.normalized_data}}

  train_job:
    type: command
    inputs:
      training_data: ${{parent.jobs.normalize_job.outputs.normalized_data}}
    outputs:
      model_output:
        mode: upload
    code: model
    environment: azureml:basic-env-scikit:2
    compute: azureml:aml-cluster
    command: >-
      python train-decision-tree.py 
      --training_data ${{inputs.training_data}} 
      --model_output ${{outputs.model_output}}



